### ISSUE TITLE
nvidia 1080 8g

### ISSUE THREAD

**Issue by AlexSpain** [3DP-The-AllFather/xelis-gpu-miner#2]
CUDA Runtime Error at: kernel.cu:700
named symbol not found
terminate called without an active exception
Nvidia driver 535
CUDA 12.2

**Comment by Alarmod** [comment]
Same with [xelis-taxminer-old](https://github.com/3DP-The-AllFather/xelis-gpu-miner/releases/download/0.5/xelis-taxminer-old)

Driver 550, CUDA 12.4
